### ISSUE TITLE
Papermc 1.13.2 support

### ISSUE THREAD

**Issue by Blackblurr** [LazyGon/JailWorker#4]
[14:17:54 ERROR]: Could not load 'plugins\JailWorker (2).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.14
        at org.bukkit.craftbukkit.v1_13_R2.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:226) ~[patched_1.13.2.jar:git-Paper-651]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:130) ~[patched_1.13.2.jar:git-Paper-651]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[patched_1.13.2.jar:git-Paper-651]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:255) ~[patched_1.13.2.jar:git-Paper-651]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:331) ~[patched_1.13.2.jar:git-Paper-651]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-651]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-651]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]

**Comment by LazyGon** [comment]
I will fix on next update!

**Comment by LazyGon** [comment]
Updated JailWorker and close here...
